language: c
compiler: gcc
install:
  - git clone https://github.com/linux-can/can-utils.git
  - cd can-utils && ./autogen.sh && ./configure && make && sudo make install && cp cangen /bin/ && cp candump /bin/
script: sudo modprobe vcan && ./embedded/examples/setupCAN.sh && make examples && make
git:
  submodules: false
