language: c
compiler: gcc
install:
  - git clone https://github.com/linux-can/can-utils.git
  - cd can-utils
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install 
  - sudo cp cangen /bin/ && sudo cp candump /bin/
  - cd ..
script: sudo modprobe vcan && ./embedded/examples/setupCAN.sh && make examples VIRTUAL=1 && make VIRTUAL=1 && ./out/tests/can_test
git:
  submodules: false
