name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: test
      run: ./deploy.sh gtest-setup && ./deploy.sh build && ./out/run_all_tests
