name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install GTest
      run: ./deploy.sh gtest-setup
    - name: Build Executables
      run: ./deploy.sh build
    - name: Run Tests
      run: ./out/run_all_tests